version: "3.8"
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=G0neFishing
    ports:
      - 14330:1433

  rabbitmq:
    image: rabbitmq:3.11.10-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
# default credentials: guest/guest
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq/container/data/:/var/lib/rabbitmq/
      - ./rabbitmq/container/log/:/var/log/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - 15672:15672
      - 5672:5672
